# Generated by Django 4.0.1 on 2022-02-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=1000, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('sex', models.CharField(max_length=1000)),
                ('matrial', models.CharField(max_length=1000)),
                ('activite', models.CharField(max_length=1000)),
                ('NomDeLaMere', models.CharField(max_length=1000)),
                ('PrenomDeLaMere', models.CharField(max_length=1000)),
                ('NomDuLaPere', models.CharField(max_length=1000)),
                ('PrenomDuLaPere', models.CharField(max_length=1000)),
                ('pays', models.CharField(max_length=1000)),
                ('ville', models.CharField(max_length=1000)),
                ('ndd', models.CharField(max_length=1000)),
                ('ddlIDCOMMUNE2', models.CharField(max_length=1000)),
                ('txtCOMMUNE2', models.CharField(max_length=1000)),
                ('quatier', models.CharField(max_length=1000)),
                ('Lieu_dit', models.CharField(max_length=1000)),
                ('Unite_de_gestion', models.CharField(max_length=1000)),
                ('tel', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
